// src/pages/PredictPage.jsx
import { useState } from "react";
import { Link, Route, Routes, useLocation } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { 
  FaBrain, 
  FaImage, 
  FaLightbulb,
  FaTimes,
  FaArrowRight,
  FaHeart,
  FaHome
} from "react-icons/fa";
import SentimentalPage from "./sentimental";
import ImageGenPage from "./image";
import CopingPage from "./copingPage";

// Import your pages


const PredictPage = () => {
  const location = useLocation();
  const [selectedFeature, setSelectedFeature] = useState(null);

  // Check if we're on the main predict page or a sub-page
  const isMainPage = location.pathname === "/predict-page" || location.pathname === "/predict-page/";

  const features = [
    {
      id: "sentimental",
      icon: <FaBrain className="text-3xl" />,
      emoji: "🧠",
      title: "Emotion Detection",
      shortDesc: "Analyze your emotions from text",
      fullDesc: "Our advanced Deep Learning model analyzes your text to accurately identify your emotional state. Simply type how you're feeling, and our AI will detect emotions like happiness, sadness, anxiety, anger, and more.",
      benefits: [
        "Accurate emotion detection using AI",
        "Understand your feelings better",
        "Get insights about your emotional patterns",
        "Quick and easy text analysis"
      ],
      color: "from-rose-500 to-pink-500",
      bgColor: "bg-rose-50",
      lightColor: "bg-rose-100",
      path: "/predict-page/sentimental"
    },
    {
      id: "gen-image",
      icon: <FaImage className="text-3xl" />,
      emoji: "🎨",
      title: "Calming Images",
      shortDesc: "AI-generated peaceful visuals",
      fullDesc: "Experience tranquility with our AI-generated calming imagery. Based on your emotional state, we create personalized peaceful visuals designed to soothe your mind and promote relaxation.",
      benefits: [
        "AI-generated peaceful scenery",
        "Personalized based on your mood",
        "Helps reduce stress and anxiety",
        "Beautiful visuals for meditation"
      ],
      color: "from-purple-500 to-indigo-500",
      bgColor: "bg-purple-50",
      lightColor: "bg-purple-100",
      path: "/predict-page/gen-image"
    },
    {
      id: "advice",
      icon: <FaLightbulb className="text-3xl" />,
      emoji: "💡",
      title: "Coping Strategies",
      shortDesc: "Personalized support & advice",
      fullDesc: "Receive personalized coping strategies generated by our Generative AI. Based on your detected emotions, we provide gentle, supportive suggestions to help you manage difficult moments and improve your well-being.",
      benefits: [
        "Personalized coping suggestions",
        "AI-powered supportive guidance",
        "Practical self-care techniques",
        "Tailored to your emotional state"
      ],
      color: "from-amber-500 to-orange-500",
      bgColor: "bg-amber-50",
      lightColor: "bg-amber-100",
      path: "/predict-page/advice"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-rose-50 via-pink-50 to-fuchsia-50">
      
      {/* Animated Background - Only show on main page */}
      {isMainPage && (
        <div className="fixed inset-0 pointer-events-none">
          <div className="absolute top-20 left-10 w-72 h-72 bg-rose-200/40 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute bottom-20 right-10 w-96 h-96 bg-pink-200/40 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-fuchsia-200/30 rounded-full blur-3xl animate-pulse"></div>
        </div>
      )}

      {/* Main Content */}
      <div className="relative z-10">
        
        {/* Show Dashboard if on main page */}
        {isMainPage ? (
          <DashboardContent 
            features={features} 
            onSelectFeature={setSelectedFeature} 
          />
        ) : (
          // Show Sub-page with Back Button
          <SubPageLayout features={features}>
            <Routes>
              <Route path="/sentimental" element={<SentimentalPage />} />
              <Route path="/gen-image" element={<ImageGenPage />} />
              <Route path="/advice" element={<CopingPage />} />
            </Routes>
          </SubPageLayout>
        )}
      </div>

      {/* Modal */}
      <FeatureModal 
        feature={selectedFeature} 
        onClose={() => setSelectedFeature(null)} 
      />
    </div>
  );
};

// ============ DASHBOARD CONTENT ============
const DashboardContent = ({ features, onSelectFeature }) => {
  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        {/* Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/80 backdrop-blur-sm rounded-full shadow-lg mb-6">
          <FaHeart className="text-rose-500 text-sm" />
          <span className="text-sm font-medium text-gray-600">Choose Your Support</span>
        </div>

        <h1 className="text-4xl sm:text-5xl font-bold text-gray-800 mb-4">
          How Can We
          <span className="block bg-gradient-to-r from-rose-500 via-pink-500 to-fuchsia-500 bg-clip-text text-transparent">
            Help You Today?
          </span>
        </h1>
        
        <p className="text-lg text-gray-600 max-w-2xl mx-auto">
          Select a feature below to begin your mental wellness journey. 
          Each tool is designed to support your emotional well-being.
        </p>
      </motion.div>

      {/* Feature Cards */}
      <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
        {features.map((feature, index) => (
          <motion.div
            key={feature.id}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
            whileHover={{ y: -10, scale: 1.02 }}
            onClick={() => onSelectFeature(feature)}
            className="cursor-pointer group"
          >
            <div className={`${feature.bgColor} rounded-3xl p-8 h-full transition-all duration-300 hover:shadow-2xl border-2 border-transparent hover:border-white`}>
              
              {/* Icon */}
              <div className={`w-20 h-20 mx-auto rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center text-white shadow-xl mb-6 group-hover:scale-110 transition-transform duration-300`}>
                <span className="text-4xl">{feature.emoji}</span>
              </div>

              {/* Content */}
              <div className="text-center">
                <h3 className="text-xl font-bold text-gray-800 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 mb-6">
                  {feature.shortDesc}
                </p>

                {/* Button */}
                <div className={`inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r ${feature.color} text-white font-medium rounded-xl shadow-lg group-hover:shadow-xl transition-all duration-300`}>
                  Learn More
                  <FaArrowRight className="text-sm group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Bottom Note */}
      <motion.p
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6 }}
        className="text-center text-gray-500 text-sm mt-12"
      >
        * All features are AI-powered and designed for emotional support, not medical diagnosis.
      </motion.p>
    </div>
  );
};

// ============ SUB-PAGE LAYOUT ============
const SubPageLayout = ({ features, children }) => {
  const location = useLocation();
  
  // Find current feature
  const currentFeature = features.find(f => location.pathname.includes(f.id) || 
    (location.pathname.includes("sentimental") && f.id === "sentimental") ||
    (location.pathname.includes("gen-image") && f.id === "gen-image") ||
    (location.pathname.includes("advice") && f.id === "advice")
  );

  return (
    <div className="min-h-screen">
      
      {/* Top Navigation Bar */}
      <div className="bg-white/80 backdrop-blur-md shadow-lg sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            
            {/* Back Button */}
            <Link 
              to="/predict-page"
              className="flex items-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-xl text-gray-700 font-medium transition-colors"
            >
              <FaHome className="text-sm" />
              <span>Back to Dashboard</span>
            </Link>

            {/* Current Feature Badge */}
            {currentFeature && (
              <div className={`flex items-center gap-2 px-4 py-2 ${currentFeature.lightColor} rounded-xl`}>
                <span className="text-xl">{currentFeature.emoji}</span>
                <span className="font-medium text-gray-700">{currentFeature.title}</span>
              </div>
            )}

            {/* Quick Navigation */}
            <div className="hidden md:flex items-center gap-2">
              {features.map((feature) => (
                <Link
                  key={feature.id}
                  to={feature.path}
                  className={`p-3 rounded-xl transition-all duration-300 ${
                    location.pathname === feature.path
                      ? `bg-gradient-to-r ${feature.color} text-white shadow-lg`
                      : `${feature.lightColor} text-gray-600 hover:scale-105`
                  }`}
                  title={feature.title}
                >
                  <span className="text-lg">{feature.emoji}</span>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Page Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        {children}
      </div>
    </div>
  );
};

// ============ FEATURE MODAL ============
const FeatureModal = ({ feature, onClose }) => {
  if (!feature) return null;

  return (
    <AnimatePresence>
      {feature && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: "spring", duration: 0.5 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
          >
            <div className="bg-white rounded-3xl shadow-2xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
              
              {/* Header */}
              <div className={`bg-gradient-to-r ${feature.color} p-6 rounded-t-3xl relative`}>
                
                {/* Close Button */}
                <button
                  onClick={onClose}
                  className="absolute top-4 right-4 w-10 h-10 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center text-white transition-colors"
                >
                  <FaTimes />
                </button>

                {/* Icon & Title */}
                <div className="text-center pt-4">
                  <div className="w-20 h-20 mx-auto bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center mb-4">
                    <span className="text-5xl">{feature.emoji}</span>
                  </div>
                  <h2 className="text-2xl font-bold text-white mb-2">
                    {feature.title}
                  </h2>
                  <p className="text-white/80">
                    {feature.shortDesc}
                  </p>
                </div>
              </div>

              {/* Body */}
              <div className="p-6">
                
                {/* Description */}
                <div className="mb-6">
                  <h3 className="text-lg font-semibold text-gray-800 mb-3">
                    About This Feature
                  </h3>
                  <p className="text-gray-600 leading-relaxed">
                    {feature.fullDesc}
                  </p>
                </div>

                {/* Benefits */}
                <div className="mb-8">
                  <h3 className="text-lg font-semibold text-gray-800 mb-3">
                    What You'll Get
                  </h3>
                  <div className="space-y-3">
                    {feature.benefits.map((benefit, index) => (
                      <motion.div
                        key={index}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className={`flex items-center gap-3 p-3 ${feature.lightColor} rounded-xl`}
                      >
                        <div className={`w-6 h-6 rounded-full bg-gradient-to-r ${feature.color} flex items-center justify-center flex-shrink-0`}>
                          <span className="text-white text-xs">✓</span>
                        </div>
                        <span className="text-gray-700">{benefit}</span>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-4">
                  <button
                    onClick={onClose}
                    className="flex-1 px-6 py-4 bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium rounded-xl transition-colors"
                  >
                    Cancel
                  </button>
                  <Link
                    to={feature.path}
                    onClick={onClose}
                    className={`flex-1 px-6 py-4 bg-gradient-to-r ${feature.color} text-white font-semibold rounded-xl shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300 flex items-center justify-center gap-2`}
                  >
                    Start Now
                    <FaArrowRight />
                  </Link>
                </div>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

export default PredictPage;